if game.PlaceId == 12480945489 then
local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()

local Window = OrionLib:MakeWindow({Name = "Elbolis Hub | [🔮MAGIC!🔮]  Tapping Fantasy!", HidePremium = false, IntroText = "Elbolis Hub", SaveConfig = true, ConfigFolder = "esbanuwu"})

--Values
_G.autoTap = true
_G.autoHatch = true
_G.selectEgg = "Basic Egg"
_G.autoHatch1 = true
_G.selectEgg1 = "ReleaseEgg"
_G.autoUpgrade = true
_G.selectUpgrade = "Pet Equipped"

--Functions

function autoTap()
    while _G.autoTap == true do
game:GetService("ReplicatedStorage").Remote:FireServer("Roll2")
    wait(.0001)
  end
end

function autoHatch()
    while _G.autoHatch == true do 
local args = {
    [1] = _G.selectEgg,
    [2] = true,
    [4] = true,
    [5] = {
        ["1"] = true,
        ["4"] = false,
        ["3"] = true,
        ["2"] = true
    }
}

game:GetService("ReplicatedStorage").Events.OpenEgg:FireServer(unpack(args))

      wait(.1)
    end
 end

function autoHatch1()
    while _G.autoHatch1 == true do 
local args = {
    [1] = _G.selectEgg1,
    [2] = true,
    [4] = true,
    [5] = {
        ["1"] = true,
        ["4"] = false,
        ["3"] = true,
        ["2"] = true
    }
}

game:GetService("ReplicatedStorage").Events.OpenEgg:FireServer(unpack(args))

      wait(.1)
    end
 end

function autoCraftAll()
    while _G.autoCraftAll == true do
game:GetService("ReplicatedStorage").Events.PetAction:InvokeServer("CraftAll")
    wait(20)
end
end

function autoUpgrade()
    while _G.autoUpgrade == true do
game:GetService("ReplicatedStorage").Functions.BuyUpgrade:InvokeServer("_G.selectUpgrade")
    wait(.1)
end
end

--Tabs
local FarmTab = Window:MakeTab({
	Name = "AutoFarm",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

local TeleportTab = Window:MakeTab({
	Name = "Teleport",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

local EggsTab = Window:MakeTab({
	Name = "Eggs",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

--Toggles
FarmTab:AddToggle({
	Name = "Auto Lick",
	Default = false,
	Callback = function(Value)
		_G.autoTap = Value
    autoTap()
	end
})

EggsTab:AddToggle({
	Name = "Auto Craft All",
	Default = false,
	Callback = function(Value)
		_G.autoCraftAll = Value
    autoCraftAll()
	end
})

EggsTab:AddToggle({
	Name = "Auto Hatch = all eggs",
	Default = false,
	Callback = function(Value)
		_G.autoHatch = Value
    autoHatch()
	end
})

EggsTab:AddToggle({
	Name = "Auto Hatch = Exclusives",
	Default = false,
	Callback = function(Value)
		_G.autoHatch1 = Value
    autoHatch1()
	end
})


-- Buttons

TeleportTab:AddButton({
	Name = "Teleport To Moon!",
	Callback = function()
      		-- Script generated by TurtleSpy, made by Intrer#0421

game:GetService("ReplicatedStorage").Events.PortalTP:FireServer("Moon")
  	end    
})

TeleportTab:AddButton({
	Name = "Teleport To Home!",
	Callback = function()
      		-- Script generated by TurtleSpy, made by Intrer#0421

game:GetService("ReplicatedStorage").Events.PortalTP:FireServer("Home")
  	end    
})
  
-- Dropdowns

EggsTab:AddDropdown({
	Name = "Select Egg",
	Default = "Basic Egg",
	Options = {"Basic Egg","Novice Egg","Advanced Egg"},
	Callback = function(Value)
		_G.selectEgg = Value
    print(_G.selectEgg)
	end
})

EggsTab:AddDropdown({
	Name = "Select Event Egg",
	Default = "Release Egg",
	Options = {"Release Egg"},
	Callback = function(Value)
		_G.selectEgg1 = Value
    print(_G.selectEgg1)
	end
})


end
OrionLib:Init()
